--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.GetPlayerInfoMsg_pb')

GETPLAYERINFOMSG = protobuf.Descriptor();
GETPLAYERINFOMSG_PLAYERID_FIELD = protobuf.FieldDescriptor();

GETPLAYERINFOMSG_PLAYERID_FIELD.name = "playerId"
GETPLAYERINFOMSG_PLAYERID_FIELD.full_name = ".pb.GetPlayerInfoMsg.playerId"
GETPLAYERINFOMSG_PLAYERID_FIELD.number = 1
GETPLAYERINFOMSG_PLAYERID_FIELD.index = 0
GETPLAYERINFOMSG_PLAYERID_FIELD.label = 2
GETPLAYERINFOMSG_PLAYERID_FIELD.has_default_value = false
GETPLAYERINFOMSG_PLAYERID_FIELD.default_value = 0
GETPLAYERINFOMSG_PLAYERID_FIELD.type = 3
GETPLAYERINFOMSG_PLAYERID_FIELD.cpp_type = 2

GETPLAYERINFOMSG.name = "GetPlayerInfoMsg"
GETPLAYERINFOMSG.full_name = ".pb.GetPlayerInfoMsg"
GETPLAYERINFOMSG.nested_types = {}
GETPLAYERINFOMSG.enum_types = {}
GETPLAYERINFOMSG.fields = {GETPLAYERINFOMSG_PLAYERID_FIELD}
GETPLAYERINFOMSG.is_extendable = false
GETPLAYERINFOMSG.extensions = {}

GetPlayerInfoMsg = protobuf.Message(GETPLAYERINFOMSG)

