--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Protol.PBVector3_pb')

PBVECTOR3 = protobuf.Descriptor();
PBVECTOR3_X_FIELD = protobuf.FieldDescriptor();
PBVECTOR3_Y_FIELD = protobuf.FieldDescriptor();
PBVECTOR3_Z_FIELD = protobuf.FieldDescriptor();

PBVECTOR3_X_FIELD.name = "x"
PBVECTOR3_X_FIELD.full_name = ".pb.PBVector3.x"
PBVECTOR3_X_FIELD.number = 1
PBVECTOR3_X_FIELD.index = 0
PBVECTOR3_X_FIELD.label = 2
PBVECTOR3_X_FIELD.has_default_value = false
PBVECTOR3_X_FIELD.default_value = 0
PBVECTOR3_X_FIELD.type = 3
PBVECTOR3_X_FIELD.cpp_type = 2

PBVECTOR3_Y_FIELD.name = "y"
PBVECTOR3_Y_FIELD.full_name = ".pb.PBVector3.y"
PBVECTOR3_Y_FIELD.number = 2
PBVECTOR3_Y_FIELD.index = 1
PBVECTOR3_Y_FIELD.label = 2
PBVECTOR3_Y_FIELD.has_default_value = false
PBVECTOR3_Y_FIELD.default_value = 0
PBVECTOR3_Y_FIELD.type = 3
PBVECTOR3_Y_FIELD.cpp_type = 2

PBVECTOR3_Z_FIELD.name = "z"
PBVECTOR3_Z_FIELD.full_name = ".pb.PBVector3.z"
PBVECTOR3_Z_FIELD.number = 3
PBVECTOR3_Z_FIELD.index = 2
PBVECTOR3_Z_FIELD.label = 2
PBVECTOR3_Z_FIELD.has_default_value = false
PBVECTOR3_Z_FIELD.default_value = 0
PBVECTOR3_Z_FIELD.type = 3
PBVECTOR3_Z_FIELD.cpp_type = 2

PBVECTOR3.name = "PBVector3"
PBVECTOR3.full_name = ".pb.PBVector3"
PBVECTOR3.nested_types = {}
PBVECTOR3.enum_types = {}
PBVECTOR3.fields = {PBVECTOR3_X_FIELD, PBVECTOR3_Y_FIELD, PBVECTOR3_Z_FIELD}
PBVECTOR3.is_extendable = false
PBVECTOR3.extensions = {}

PBVector3 = protobuf.Message(PBVECTOR3)

