--Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local PBVector3_pb = require("Protol.PBVector3_pb")
module('Protol.PlayerInfoMsg_pb')

PLAYERINFOMSG = protobuf.Descriptor();
PLAYERINFOMSG_PLAYERID_FIELD = protobuf.FieldDescriptor();
PLAYERINFOMSG_NAME_FIELD = protobuf.FieldDescriptor();
PLAYERINFOMSG_POS_FIELD = protobuf.FieldDescriptor();

PLAYERINFOMSG_PLAYERID_FIELD.name = "playerId"
PLAYERINFOMSG_PLAYERID_FIELD.full_name = ".pb.PlayerInfoMsg.playerId"
PLAYERINFOMSG_PLAYERID_FIELD.number = 1
PLAYERINFOMSG_PLAYERID_FIELD.index = 0
PLAYERINFOMSG_PLAYERID_FIELD.label = 2
PLAYERINFOMSG_PLAYERID_FIELD.has_default_value = false
PLAYERINFOMSG_PLAYERID_FIELD.default_value = 0
PLAYERINFOMSG_PLAYERID_FIELD.type = 3
PLAYERINFOMSG_PLAYERID_FIELD.cpp_type = 2

PLAYERINFOMSG_NAME_FIELD.name = "name"
PLAYERINFOMSG_NAME_FIELD.full_name = ".pb.PlayerInfoMsg.name"
PLAYERINFOMSG_NAME_FIELD.number = 2
PLAYERINFOMSG_NAME_FIELD.index = 1
PLAYERINFOMSG_NAME_FIELD.label = 2
PLAYERINFOMSG_NAME_FIELD.has_default_value = false
PLAYERINFOMSG_NAME_FIELD.default_value = ""
PLAYERINFOMSG_NAME_FIELD.type = 9
PLAYERINFOMSG_NAME_FIELD.cpp_type = 9

PLAYERINFOMSG_POS_FIELD.name = "pos"
PLAYERINFOMSG_POS_FIELD.full_name = ".pb.PlayerInfoMsg.pos"
PLAYERINFOMSG_POS_FIELD.number = 3
PLAYERINFOMSG_POS_FIELD.index = 2
PLAYERINFOMSG_POS_FIELD.label = 2
PLAYERINFOMSG_POS_FIELD.has_default_value = false
PLAYERINFOMSG_POS_FIELD.default_value = nil
PLAYERINFOMSG_POS_FIELD.message_type = PBVector3_pb.PBVECTOR3
PLAYERINFOMSG_POS_FIELD.type = 11
PLAYERINFOMSG_POS_FIELD.cpp_type = 10

PLAYERINFOMSG.name = "PlayerInfoMsg"
PLAYERINFOMSG.full_name = ".pb.PlayerInfoMsg"
PLAYERINFOMSG.nested_types = {}
PLAYERINFOMSG.enum_types = {}
PLAYERINFOMSG.fields = {PLAYERINFOMSG_PLAYERID_FIELD, PLAYERINFOMSG_NAME_FIELD, PLAYERINFOMSG_POS_FIELD}
PLAYERINFOMSG.is_extendable = false
PLAYERINFOMSG.extensions = {}

PlayerInfoMsg = protobuf.Message(PLAYERINFOMSG)

